name: quality

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: sbt/setup-sbt@v1
      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli
      - run: sbt scalafmtCheckAll
      - run: sbt scalafix
      - run: typos
      - run: sbt compile
      - run: sbt test
