name: quality

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - name: Install typos
        uses: taiki-e/install-action@v2
        with:
          tool: typos-cli
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze
      - run: typos
      - run: dart test
