// Scalafix configuration — enforced by noslop
rules = [
  DisableSyntax
  LeakingImplicitClassVal
  NoAutoTupling
  ProcedureSyntax
  RemoveUnused
]

DisableSyntax.noVars = true
DisableSyntax.noThrows = false
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = false
DisableSyntax.noAsInstanceOf = false
DisableSyntax.noIsInstanceOf = false
DisableSyntax.noXml = true
DisableSyntax.noDefaultArgs = false
DisableSyntax.noFinallyBlock = false
